FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y docker.io

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt