# Generated by Django 4.1.7 on 2025-10-27 19:01

import django.core.validators
from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(null=True, upload_to='shop/images', validators=[shop.validators.validate_image_size])),
            ],
        ),
    ]
