jenkins:
  systemMessage: "Jenkins is configured via JCasC"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('onlineshop') {
        description('CI/CD pipeline for OnlineShop')

        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Zakjer/OnlineShop.git')
                  credentials('github-creds')
                }
                branch('jenkins_test')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github-creds
              username: github-user
              password: github-token
              description: GitHub access token

unclassified:
  location:
    url: http://localhost:8000
