jenkins:
  systemMessage: "Jenkins is configured via JCasC"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - file:
              id: azure-creds
              description: "Azure Service Principal JSON"
              fileName: az-creds.json
              scope: GLOBAL


jobs:
  - script: >
      pipelineJob('OnlineShop-automation') {
        description('CI/CD pipeline for OnlineShop')

        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Zakjer/OnlineShop.git')
                }
                branch('jenkins_test')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

unclassified:
  location:
    url: http://localhost:8000
